version: '3'

services:
  bot:
    image: ghcr.io/learnspigot/discord-bot:latest
    pull_policy: always
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#restart_policy
    # Other options are not needed for this setup.
    volumes:
      - ./data.json:/app/data.json
    deploy:
      restart_policy:
        condition: none # Not sure if we are given an exit code by the JVM.
        delay: 30s
    env_file:
      - .env.docker
