package com.learnspigot.bot.counting

object CountingInsults {
    val fuckedUpInsults = listOf(
        "Were you counting with your eyes closed?",
        "Did you mistake numbers for alphabet letters?",
        "Are you allergic to numbers, or just incompetent?",
        "Did you skip math class to skip numbers?",
        "Your counting skills are like a broken record—stuck on repeat.",
        "Were you counting with your fingers in your ears?",
        "Even a toddler could count better than that.",
        "I've seen smoother counting from a malfunctioning calculator.",
        "Did you confuse counting with alphabetizing?",
        "Did you lose count because you ran out of fingers?",
        "You must have a PhD in miscounting.",
        "Were you using an abacus with missing beads?",
        "Your counting is about as accurate as a blindfolded archer.",
        "I've heard better counting from a parrot with a limited vocabulary.",
        "Did you forget to engage your brain while counting?",
        "Your counting proficiency rivals that of a distracted squirrel.",
        "Did you fall asleep halfway through counting?",
        "You're counting like you're trying to navigate a maze blindfolded.",
        "I didn't know counting could be done with such remarkable ineptitude.",
        "I've seen smoother counting from a broken clock.",
        "Were you distracted by counting sheep instead of numbers?",
        "Did you skip numbers like a stone skips on a pond?",
        "Your counting is as shaky as a Jenga tower in an earthquake.",
        "Did you misplace your counting skills along with your common sense?",
        "Even a GPS would struggle to follow your counting route.",
        "You're counting like you're allergic to the correct number.",
        "Your skills are like a GPS without signal—completely lost.",
        "Did you confuse counting with playing hopscotch?",
        "You're counting like you're going for the world record in mistakes per minute.",
        "Did you accidentally count your own mistakes?",
        "You're like a toddler on roller skates—everywhere but straight.",
        "Did you count backwards instead of forwards?",
        "Your counting is like a Picasso painting—abstract and confusing.",
        "Did you mistake counting for a memory test?",
        "You're counting like you're decoding ancient hieroglyphics.",
        "Did you misplace your counting marbles?",
        "Your accuracy is on par with a Magic 8-Ball reading.",
        "Were you trying to count on a roller coaster?",
        "You're counting like you're trying to break the sound barrier—fast, but out of control.",
        "Did you confuse counting with a game of roulette?",
        "Your skills are like a GPS with dead batteries—going nowhere.",
        "Were you trying to count while juggling flaming torches?",
        "Did you accidentally count in a foreign language?",
        "Your abilities are as consistent as spring weather—completely unpredictable.",
        "Did you mistake counting for Whac-A-Mole?",
        "You're counting like you're solving a Rubik’s Cube blindfolded.",
        "Did you forget how to count and just start guessing?",
        "Your counting is like a broken compass—any direction but the right one.",
        "Were you trying to count while riding a unicycle on a tightrope?",
        "Did you mistakenly count your imaginary friends?"
    )

    val deletedCountInsults = listOf(
        "Wow, deleted your count? That number must've been *too* advanced for you.",
        "You treat numbers like bad tweets—delete and deny.",
        "Nice, you rage-quit a number. Powerful move.",
        "You really hit 'Ctrl + Z' on math.",
        "Was that number too emotionally damaging to keep?",
        "You just ghosted a number. Savage.",
        "Even numbers deserve closure—don’t just delete and run.",
        "Ah yes, the legendary disappearing digit technique.",
        "You deleted a number like it owed you money.",
        "Was that a rage delete or a cry-for-help delete?",
        "Congrats, you made the number system unstable.",
        "That number didn't deserve this betrayal.",
        "Even your mistakes are afraid of commitment.",
        "Your counting has a higher casualty rate than a soap opera.",
        "Mathematics just filed a restraining order.",
        "You just performed a statistical hit-and-run.",
        "Is your delete key sponsored by chaos?",
        "That number's gonna need therapy after what you just did.",
        "You deleted it like it was evidence.",
        "Bold move—treating numbers like disposable tissues.",
        "You counted so wrong, you tried to erase history.",
        "That number didn’t deserve to be ghosted like your ex.",
        "The number didn’t fail you—you failed the number.",
        "We all saw it. No amount of deleting will save you now.",
        "This isn’t your diary—you can’t just erase the past.",
        "If numbers had feelings, you just broke one’s heart.",
        "Deleting your count won’t delete your shame.",
        "Even the number line flinched when you hit delete.",
        "You speedran invalidating your own contribution.",
        "You didn’t delete a count—you committed numerical murder."
    )

    val doubleCountInsults = listOf(
        "Did you forget you already counted that?",
        "Are you hoping the numbers will change if you count again?",
        "You must really love that number to count it twice.",
        "Did you hit replay on your counting?",
        "Is double-counting your secret strategy now?",
        "I didn’t realize this was the counting remix.",
        "Did you accidentally press repeat on your counting machine?",
        "Guess once just wasn’t enough for you.",
        "You're like a broken record—but with numbers.",
        "Are you waiting for the number to change its mind?",
        "Your counting is pure déjà vu—heard it all before.",
        "Training for the counting Olympics with extra laps?",
        "You thought we wouldn’t notice?",
        "Double trouble takes on a new meaning with you.",
        "Did you get lost on your way back to the first number?",
        "You’re like a dog chasing its tail—but with digits.",
        "Did you hit rewind on your brain mid-count?",
        "Congrats, you doubled the work for no reason.",
        "You're like a broken clock—always off, yet repetitive.",
        "Is this your strategy to make numbers fear you?",
        "Did you think the numbers were playing hide and seek?",
        "Is this number insurance—just in case you messed up the first one?",
        "You're like a magician pulling out the same rabbit twice.",
        "Did you accidentally hit repeat on your counting playlist?",
        "This sequel’s worse than the original.",
        "Did you think the numbers would talk back if you asked nicely?",
        "You're like a detective solving the same case twice.",
        "Did you think the number disappeared the first time?",
        "Guess you just wanted a second chance to fail.",
        "Trying to create job security for counters, huh?",
        "Your counting is the Groundhog Day of disasters.",
        "Did you refresh your brain mid-count?",
        "You're like a broken vending machine—same thing every time.",
        "Your numbers are stuck in a time loop.",
        "Nobody asked for a rerun.",
        "Trying to catch a disappearing number with repetition?",
        "You're like a kid yelling 'are we there yet?'—but numeric.",
        "Did you expect different results the second time?"
    )
}
